Book suggestion model added
wolox-training/st-rails pull request #17
Opened 2018-12-17 21:25 UTC by storresy

**Summary**
- Added book suggestion migration
- Added validations for book suggestion model
- Added belongs to user optional relation

**Trello Card**
https://trello.com/c/CG9rmHyJ

**Screenshots**
<img width="1069" alt="screen shot 2018-12-17 at 18 03 10" src="https://user-images.githubusercontent.com/6606379/50121299-58013e00-0226-11e9-964b-2ba5bdc3b2f5.png">

2018-12-18 17:00 UTC, Gmarn requested changes

2018-12-18 17:00 UTC, Gmarn commented on db/schema.rb
> +    t.datetime "created_at"
Usually time stamp are like this
```suggestion
     t.datetime "created_at", null: false
```

2018-12-18 17:00 UTC, Gmarn commented on db/schema.rb
> +    t.datetime "updated_at"
Same

2018-12-18 17:00 UTC, Gmarn commented on db/migrate/20181217230131_add_time_stamps_to_book_suggestion.rb
> +  def change
Just with that you have the expected behaviour?

2018-12-18 17:00 UTC, Gmarn commented on app/models/book_suggestion.rb
> +  belongs_to :user, optional: true
And the equivalent in User?

2018-12-18 18:28 UTC, storresy commented on db/schema.rb
> +    t.datetime "created_at"
Yes, but I have previously pushed the table creation without timestamps, so if I add the not null constraint without a default value, that migration will fail if there are book suggestions in the database. In this case that would not cause any issue since i'm the only one coding in this repo, but in a real project that could cause a problem. How do you suggest to face this issue ?

2018-12-18 18:30 UTC, storresy commented on db/migrate/20181217230131_add_time_stamps_to_book_suggestion.rb
> +  def change
Yes 😃 
See the screenshots attached to the PR description to confirm that Rails is really updating those fields when creating/updating a book suggestion.

2018-12-18 19:15 UTC, storresy commented on app/models/book_suggestion.rb
> +  belongs_to :user, optional: true
Fixed

2018-12-19 13:51 UTC, Gmarn approved these changes

2018-12-19 14:13 UTC, merged