Added book model
wolox-training/st-rails pull request #6
Opened 2018-12-10 15:14 UTC by storresy

**Summary**
- Created book migration
- Added book model validations

**Trello Card**
https://trello.com/c/M0oLNzqW

**Screenshots**
<img width="1137" alt="screen shot 2018-12-10 at 10 04 26" src="https://user-images.githubusercontent.com/6606379/49741210-e8a6af80-fc63-11e8-8030-1b2dd0881b27.png">

2018-12-10 18:09 UTC, lmasello submitted a review, later dismissed

2018-12-10 18:09 UTC, lmasello commented on db/migrate/20181210145503_create_books.rb
> +      t.string :title
Don't forget to add the null constraint so that the model and the db are consistent.

2018-12-10 18:10 UTC, Gmarn requested changes

2018-12-10 18:10 UTC, Gmarn commented on db/migrate/20181210145503_create_books.rb
> +      t.string :title
Seems you forgot to add database validation for required field.

2018-12-10 18:10 UTC, Gmarn commented on db/migrate/20181210145503_create_books.rb
> +      t.string :title
Remember, `never modify a migration`

2018-12-11 12:12 UTC, Gmarn approved these changes

2018-12-11 15:09 UTC, merged